development:
  stripe_secret_key: 'sk_test_51J9jANA17mXu1qhUy6I7Iq5WDRlP8FUy1dWeOSOcvAkuNYaTFIbmzxSNpALRGAhjxRwmv38mNj1sg1uZSafyxFLY006HEIAqwO'
  stripe_publishable_key: 'pk_test_51J9jANA17mXu1qhUqAaY9HmhnzGec9X4UmCgDVWv6kAVb0hipNnu5p3gEEAHsyykOnIxe0nrm3BYq2sHZmol8v1800RnZvGimu'

production:
  stripe_secret_key: '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'
  stripe_publishable_key: 'pk_live_51J9jANA17mXu1qhUoLYnGE7MGbqGH14KK2bLBCuoIOk1BEPUcHW6q8qW8QECXshPzkQv6MwWP9ljmVifsFItXvli00O9Z3lDs0'